services:
  simplex-bridge:
    image: ghcr.io/libre-7/simplex-bridge@sha256:04cdd16a4315df11fd1c44d3ea26ffc17cc75b8d33249ba2d5987a7900911153 # v0.16.0
    container_name: simplex-bridge
    network_mode: host
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - simplex-data:/data
    environment:
      SIMPLEX_DISPLAY_NAME: "Simplex Bridge"
      SIMPLEX_AUTO_ACCEPT: "true"
      SIMPLEX_FILES_ENABLED: "true"
      SIMPLEX_MARK_READ: "true"
      SIMPLEX_TOR: "false"
      TZ: "UTC"
    restart: unless-stopped

volumes:
  simplex-data:
